name: 'Ralph CLI Action'
description: 'Autonomous coding loop for Claude Code. PRD-based workflow with bash implementation.'
author: 'AskTinNguyen'

branding:
  icon: 'code'
  color: 'purple'

inputs:
  command:
    description: 'Ralph command to run (build, plan, prd)'
    required: false
    default: 'build'
  iterations:
    description: 'Number of build iterations to run'
    required: false
    default: '5'
  agent:
    description: 'AI agent to use (claude, codex, droid)'
    required: false
    default: 'claude'
  prd:
    description: 'PRD number to build (uses latest if not specified)'
    required: false
    default: ''
  api-key:
    description: 'Agent API key (e.g., ANTHROPIC_API_KEY for Claude)'
    required: true
  working-directory:
    description: 'Working directory for ralph commands'
    required: false
    default: '.'
  no-commit:
    description: 'Skip automatic git commits during build'
    required: false
    default: 'false'

outputs:
  success:
    description: 'Whether the build completed successfully (true/false)'
    value: ${{ steps.ralph-run.outputs.success }}
  stories-completed:
    description: 'Number of user stories completed in this run'
    value: ${{ steps.ralph-run.outputs.stories_completed }}
  duration:
    description: 'Duration of the build in seconds'
    value: ${{ steps.ralph-run.outputs.duration }}
  exit-code:
    description: 'Exit code from ralph command'
    value: ${{ steps.ralph-run.outputs.exit_code }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install ralph-cli
      shell: bash
      run: |
        npm install -g ralph-cli || npm install -g .
        ralph --help || echo "Ralph installed"

    - name: Run Ralph
      id: ralph-run
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ANTHROPIC_API_KEY: ${{ inputs.api-key }}
        OPENAI_API_KEY: ${{ inputs.api-key }}
        RALPH_AGENT: ${{ inputs.agent }}
        RALPH_CI: 'true'
      run: |
        # Source the entrypoint script
        source "${{ github.action_path }}/action/entrypoint.sh"

        # Run ralph with provided options
        run_ralph \
          "${{ inputs.command }}" \
          "${{ inputs.iterations }}" \
          "${{ inputs.agent }}" \
          "${{ inputs.prd }}" \
          "${{ inputs.no-commit }}"
