codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 70%
        threshold: 10%

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

flags:
  unittests:
    paths:
      - tests/
    carryforward: true
