/**
 * Bash completion generator for ralph CLI
 *
 * Generates a bash completion script that provides:
 * - Command completion (build, plan, prd, stream, etc.)
 * - Flag completion (--prd, --agent, --no-commit)
 * - Dynamic PRD number completion from .ralph/PRD-* directories
 * - Agent name completion (claude/codex/droid)
 */

/**
 * All available ralph commands
 */
const COMMANDS = [
  "build",
  "plan",
  "prd",
  "stream",
  "install",
  "ping",
  "status",
  "doctor",
  "init",
  "watch",
  "eval",
  "estimate",
  "improve",
  "registry",
  "search",
  "import",
  "stats",
  "optimize",
  "diagnose",
  "ui",
  "checkpoint",
  "help",
  "log",
  "completions",
];

/**
 * Stream subcommands
 */
const STREAM_SUBCOMMANDS = [
  "new",
  "list",
  "status",
  "init",
  "build",
  "merge",
  "cleanup",
];

/**
 * Registry subcommands
 */
const REGISTRY_SUBCOMMANDS = ["add", "list", "remove", "update"];

/**
 * Import subcommands
 */
const IMPORT_SUBCOMMANDS = ["guardrails"];

/**
 * Optimize subcommands
 */
const OPTIMIZE_SUBCOMMANDS = ["prompts"];

/**
 * Available agent names
 */
const AGENTS = ["claude", "codex", "droid"];

/**
 * Build command flags
 */
const BUILD_FLAGS = [
  "--prd",
  "--agent",
  "--no-commit",
  "--no-retry",
  "--resume",
];

/**
 * Plan command flags
 */
const PLAN_FLAGS = ["--prd"];

/**
 * PRD command flags
 */
const PRD_FLAGS = ["--out"];

/**
 * Estimate command flags
 */
const ESTIMATE_FLAGS = ["--prd", "--json", "--pricing", "--model", "--accuracy"];

/**
 * Doctor command flags
 */
const DOCTOR_FLAGS = ["--verbose", "-v", "--json", "--fix"];

/**
 * UI command flags
 */
const UI_FLAGS = ["--open"];

/**
 * Stats command flags
 */
const STATS_FLAGS = ["--global", "-g", "--json", "--no-cache", "--tokens"];

/**
 * Search command flags
 */
const SEARCH_FLAGS = [
  "--project",
  "--type",
  "--tags",
  "--since",
  "--limit",
  "--rebuild",
];

/**
 * Install command flags
 */
const INSTALL_FLAGS = ["--skills", "--force", "--import-from"];

/**
 * Diagnose command flags
 */
const DIAGNOSE_FLAGS = ["--run", "--json", "--limit"];

/**
 * Import guardrails flags
 */
const IMPORT_GUARDRAILS_FLAGS = ["--from", "--all"];

/**
 * Optimize prompts flags
 */
const OPTIMIZE_PROMPTS_FLAGS = ["--apply", "--versions"];

/**
 * Completions command flags
 */
const COMPLETIONS_FLAGS = ["--install"];

/**
 * Model options for estimate command
 */
const MODELS = ["opus", "sonnet", "haiku"];

/**
 * Generate the complete bash completion script
 * @returns {string} The bash completion script
 */
function generate() {
  return `#!/bin/bash
# Bash completion for ralph CLI
# Generated by ralph completions bash
#
# To install:
#   ralph completions bash > ~/.local/share/bash-completion/completions/ralph
#   OR
#   ralph completions bash >> ~/.bashrc && source ~/.bashrc

# Get list of PRD numbers from .ralph/PRD-* directories
_ralph_get_prd_numbers() {
  local ralph_dir=".ralph"
  if [[ -d "$ralph_dir" ]]; then
    for dir in "$ralph_dir"/PRD-*; do
      if [[ -d "$dir" ]]; then
        basename "$dir" | sed 's/PRD-//'
      fi
    done
  fi
}

# Get list of worktree PRD numbers for stream commands
_ralph_get_worktree_prds() {
  local worktrees_dir=".ralph/worktrees"
  if [[ -d "$worktrees_dir" ]]; then
    for dir in "$worktrees_dir"/PRD-*; do
      if [[ -d "$dir" ]]; then
        basename "$dir" | sed 's/PRD-//'
      fi
    done
  fi
}

# Main completion function
_ralph_completions() {
  local cur prev words cword
  _init_completion || return

  local commands="${COMMANDS.join(" ")}"
  local stream_subcmds="${STREAM_SUBCOMMANDS.join(" ")}"
  local registry_subcmds="${REGISTRY_SUBCOMMANDS.join(" ")}"
  local import_subcmds="${IMPORT_SUBCOMMANDS.join(" ")}"
  local optimize_subcmds="${OPTIMIZE_SUBCOMMANDS.join(" ")}"
  local agents="${AGENTS.join(" ")}"
  local models="${MODELS.join(" ")}"

  # Handle flag value completion
  case "$prev" in
    --agent)
      COMPREPLY=($(compgen -W "$agents" -- "$cur"))
      return
      ;;
    --prd)
      local prd_nums=$(_ralph_get_prd_numbers)
      COMPREPLY=($(compgen -W "$prd_nums" -- "$cur"))
      return
      ;;
    --model)
      COMPREPLY=($(compgen -W "$models" -- "$cur"))
      return
      ;;
    --type)
      COMPREPLY=($(compgen -W "guardrail progress evaluation run" -- "$cur"))
      return
      ;;
    --from|--import-from|--project)
      # These expect arbitrary values, provide no completion
      return
      ;;
    --out|--plan|--progress|--run)
      # File path completion
      _filedir
      return
      ;;
  esac

  # Handle --flag=value style completion
  if [[ "$cur" == --agent=* ]]; then
    local prefix="\${cur%=*}="
    local value="\${cur#*=}"
    COMPREPLY=($(compgen -W "$agents" -- "$value"))
    COMPREPLY=("\${COMPREPLY[@]/#/$prefix}")
    return
  fi

  if [[ "$cur" == --prd=* ]]; then
    local prefix="\${cur%=*}="
    local value="\${cur#*=}"
    local prd_nums=$(_ralph_get_prd_numbers)
    COMPREPLY=($(compgen -W "$prd_nums" -- "$value"))
    COMPREPLY=("\${COMPREPLY[@]/#/$prefix}")
    return
  fi

  if [[ "$cur" == --model=* ]]; then
    local prefix="\${cur%=*}="
    local value="\${cur#*=}"
    COMPREPLY=($(compgen -W "$models" -- "$value"))
    COMPREPLY=("\${COMPREPLY[@]/#/$prefix}")
    return
  fi

  # Determine context based on previous words
  local cmd=""
  local subcmd=""
  local i=1
  while [[ $i -lt $cword ]]; do
    case "\${words[$i]}" in
      build|plan|prd|stream|install|ping|status|doctor|init|watch|eval|estimate|improve|registry|search|import|stats|optimize|diagnose|ui|checkpoint|help|log|completions)
        if [[ -z "$cmd" ]]; then
          cmd="\${words[$i]}"
        fi
        ;;
      new|list|status|init|build|merge|cleanup|add|remove|update|guardrails|prompts)
        if [[ -n "$cmd" && -z "$subcmd" ]]; then
          subcmd="\${words[$i]}"
        fi
        ;;
    esac
    ((i++))
  done

  # Complete based on command context
  case "$cmd" in
    "")
      # No command yet, complete commands
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "--help --version" -- "$cur"))
      else
        COMPREPLY=($(compgen -W "$commands" -- "$cur"))
      fi
      ;;
    build)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${BUILD_FLAGS.join(" ")}" -- "$cur"))
      else
        # Numeric argument (iterations)
        COMPREPLY=()
      fi
      ;;
    plan)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${PLAN_FLAGS.join(" ")}" -- "$cur"))
      fi
      ;;
    prd)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${PRD_FLAGS.join(" ")}" -- "$cur"))
      fi
      ;;
    stream)
      case "$subcmd" in
        "")
          # No subcommand yet
          if [[ "$cur" == -* ]]; then
            COMPREPLY=()
          else
            COMPREPLY=($(compgen -W "$stream_subcmds" -- "$cur"))
          fi
          ;;
        init|build|merge|cleanup)
          # These take a PRD number
          if [[ "$cur" == -* ]]; then
            COMPREPLY=()
          else
            local prd_nums=$(_ralph_get_prd_numbers)
            COMPREPLY=($(compgen -W "$prd_nums" -- "$cur"))
          fi
          ;;
        *)
          COMPREPLY=()
          ;;
      esac
      ;;
    registry)
      case "$subcmd" in
        "")
          COMPREPLY=($(compgen -W "$registry_subcmds" -- "$cur"))
          ;;
        add|list)
          if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "--tags" -- "$cur"))
          fi
          ;;
        *)
          COMPREPLY=()
          ;;
      esac
      ;;
    import)
      case "$subcmd" in
        "")
          COMPREPLY=($(compgen -W "$import_subcmds" -- "$cur"))
          ;;
        guardrails)
          if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "${IMPORT_GUARDRAILS_FLAGS.join(" ")}" -- "$cur"))
          fi
          ;;
        *)
          COMPREPLY=()
          ;;
      esac
      ;;
    optimize)
      case "$subcmd" in
        "")
          COMPREPLY=($(compgen -W "$optimize_subcmds" -- "$cur"))
          ;;
        prompts)
          if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "${OPTIMIZE_PROMPTS_FLAGS.join(" ")}" -- "$cur"))
          fi
          ;;
        *)
          COMPREPLY=()
          ;;
      esac
      ;;
    estimate)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${ESTIMATE_FLAGS.join(" ")}" -- "$cur"))
      fi
      ;;
    doctor)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${DOCTOR_FLAGS.join(" ")}" -- "$cur"))
      fi
      ;;
    diagnose)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${DIAGNOSE_FLAGS.join(" ")}" -- "$cur"))
      fi
      ;;
    ui)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${UI_FLAGS.join(" ")}" -- "$cur"))
      fi
      ;;
    stats)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${STATS_FLAGS.join(" ")}" -- "$cur"))
      fi
      ;;
    search)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${SEARCH_FLAGS.join(" ")}" -- "$cur"))
      fi
      ;;
    install)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${INSTALL_FLAGS.join(" ")}" -- "$cur"))
      fi
      ;;
    completions)
      if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "${COMPLETIONS_FLAGS.join(" ")}" -- "$cur"))
      else
        COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
      fi
      ;;
    *)
      COMPREPLY=()
      ;;
  esac
}

# Use _init_completion if available (bash-completion package)
# Fall back to basic completion if not
if ! type _init_completion &>/dev/null; then
  _init_completion() {
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    words=("\${COMP_WORDS[@]}")
    cword=$COMP_CWORD
  }
  _filedir() {
    COMPREPLY=($(compgen -f -- "$cur"))
  }
fi

complete -F _ralph_completions ralph
`;
}

module.exports = {
  generate,
  COMMANDS,
  STREAM_SUBCOMMANDS,
  REGISTRY_SUBCOMMANDS,
  IMPORT_SUBCOMMANDS,
  OPTIMIZE_SUBCOMMANDS,
  AGENTS,
  BUILD_FLAGS,
  MODELS,
};
