#!/bin/bash
# Ralph Stream Management - Multi-PRD parallel execution
# Usage:
#   stream.sh new ["description"]     Create new stream (prd-N)
#   stream.sh list                    List all streams
#   stream.sh status                  Show detailed status
#   stream.sh init <N>                Initialize worktree for stream
#   stream.sh build <N> [iters]       Run build in stream
#   stream.sh merge <N>               Merge completed stream

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${RALPH_ROOT:-$(pwd)}" && pwd)"
RALPH_DIR="$ROOT_DIR/.ralph"
WORKTREES_DIR="$RALPH_DIR/worktrees"
LOCKS_DIR="$RALPH_DIR/locks"

# ============================================================================
# Helpers
# ============================================================================

get_next_stream_id() {
  local max=0
  if [[ -d "$RALPH_DIR" ]]; then
    for dir in "$RALPH_DIR"/prd-*; do
      if [[ -d "$dir" ]]; then
        local num="${dir##*prd-}"
        if [[ "$num" =~ ^[0-9]+$ ]] && (( num > max )); then
          max=$num
        fi
      fi
    done
  fi
  echo $((max + 1))
}

normalize_stream_id() {
  local input="$1"
  if [[ "$input" =~ ^[0-9]+$ ]]; then
    echo "prd-$input"
  elif [[ "$input" =~ ^prd-[0-9]+$ ]]; then
    echo "$input"
  else
    echo ""
  fi
}

stream_exists() {
  local stream_id="$1"
  [[ -d "$RALPH_DIR/$stream_id" ]]
}

worktree_exists() {
  local stream_id="$1"
  [[ -d "$WORKTREES_DIR/$stream_id" ]]
}

is_stream_running() {
  local stream_id="$1"
  local lock_file="$LOCKS_DIR/$stream_id.lock"
  if [[ -f "$lock_file" ]]; then
    local pid
    pid=$(cat "$lock_file")
    if kill -0 "$pid" 2>/dev/null; then
      return 0
    fi
  fi
  return 1
}

acquire_lock() {
  local stream_id="$1"
  mkdir -p "$LOCKS_DIR"
  local lock_file="$LOCKS_DIR/$stream_id.lock"

  if is_stream_running "$stream_id"; then
    echo "Stream $stream_id is already running" >&2
    return 1
  fi

  echo $$ > "$lock_file"
  return 0
}

release_lock() {
  local stream_id="$1"
  rm -f "$LOCKS_DIR/$stream_id.lock"
}

get_stream_status() {
  local stream_id="$1"
  local stream_dir="$RALPH_DIR/$stream_id"

  if [[ ! -d "$stream_dir" ]]; then
    echo "not_found"
    return
  fi

  if is_stream_running "$stream_id"; then
    echo "running"
    return
  fi

  # Check if all stories are done by looking at PRD
  local prd_file="$stream_dir/prd.md"
  if [[ ! -f "$prd_file" ]]; then
    echo "no_prd"
    return
  fi

  local total remaining
  total=$(grep -c '### \[' "$prd_file" 2>/dev/null || echo 0)
  remaining=$(grep -c '### \[ \]' "$prd_file" 2>/dev/null || echo 0)

  if [[ "$total" -eq 0 ]]; then
    echo "no_stories"
  elif [[ "$remaining" -eq 0 ]]; then
    echo "completed"
  else
    echo "ready"
  fi
}

count_stories() {
  local prd_file="$1"
  if [[ -f "$prd_file" ]]; then
    local total remaining
    total=$(grep -c '### \[' "$prd_file" 2>/dev/null || echo 0)
    remaining=$(grep -c '### \[ \]' "$prd_file" 2>/dev/null || echo 0)
    local done=$((total - remaining))
    echo "$done/$total"
  else
    echo "0/0"
  fi
}

# ============================================================================
# Commands
# ============================================================================

cmd_new() {
  local description="${1:-}"
  local stream_num
  stream_num=$(get_next_stream_id)
  local stream_id="prd-$stream_num"
  local stream_dir="$RALPH_DIR/$stream_id"

  mkdir -p "$stream_dir/runs"

  # Create empty state files
  touch "$stream_dir/progress.md"
  touch "$stream_dir/errors.log"
  touch "$stream_dir/activity.log"

  # Create PRD template
  cat > "$stream_dir/prd.md" << 'EOF'
# Product Requirements Document

## Overview

<!-- Describe what this stream/feature is about -->

## User Stories

### [ ] US-001: First story
**As a** user
**I want** feature
**So that** benefit

#### Acceptance Criteria
- [ ] Criterion 1
- [ ] Criterion 2

EOF

  # Create plan template
  cat > "$stream_dir/plan.md" << 'EOF'
# Implementation Plan

<!-- Generated by ralph stream plan -->

EOF

  echo "Created stream: $stream_id"
  echo "  $RALPH_DIR/$stream_id/"
  echo ""
  echo "Next steps:"
  echo "  1. Edit PRD: $stream_dir/prd.md"
  echo "  2. Generate plan: ralph stream plan $stream_num"
  echo "  3. Run build: ralph stream build $stream_num"

  # Return just the number for scripting
  echo ""
  echo "Stream ID: $stream_num"
}

cmd_list() {
  if [[ ! -d "$RALPH_DIR" ]]; then
    echo "No .ralph/ directory found."
    return
  fi

  local found=0
  echo "Ralph Streams:"
  echo ""

  for dir in "$RALPH_DIR"/prd-*; do
    if [[ -d "$dir" ]]; then
      found=1
      local stream_id="${dir##*/}"
      local num="${stream_id##prd-}"
      local status
      status=$(get_stream_status "$stream_id")
      local progress
      progress=$(count_stories "$dir/prd.md")

      local symbol
      case "$status" in
        running)    symbol="▶" ;;
        completed)  symbol="●" ;;
        ready)      symbol="○" ;;
        no_prd)     symbol="?" ;;
        no_stories) symbol="?" ;;
        *)          symbol="?" ;;
      esac

      printf "  %s prd-%s  [%-10s]  %s stories\n" "$symbol" "$num" "$status" "$progress"
    fi
  done

  if [[ $found -eq 0 ]]; then
    echo "  No streams found."
    echo ""
    echo "Create one with: ralph stream new"
  fi
}

cmd_status() {
  echo ""
  echo "Ralph Multi-Stream Status"
  echo "════════════════════════════════════════════════════════"
  printf "  %-10s %-12s %-10s %-10s\n" "STREAM" "STATUS" "PROGRESS" "WORKTREE"
  echo "────────────────────────────────────────────────────────"

  if [[ ! -d "$RALPH_DIR" ]]; then
    echo "  No streams found."
    echo "────────────────────────────────────────────────────────"
    return
  fi

  for dir in "$RALPH_DIR"/prd-*; do
    if [[ -d "$dir" ]]; then
      local stream_id="${dir##*/}"
      local status
      status=$(get_stream_status "$stream_id")
      local progress
      progress=$(count_stories "$dir/prd.md")
      local has_worktree="no"
      if worktree_exists "$stream_id"; then
        has_worktree="yes"
      fi

      local symbol
      case "$status" in
        running)    symbol="▶" ;;
        completed)  symbol="●" ;;
        ready)      symbol="○" ;;
        *)          symbol="?" ;;
      esac

      printf "  %s %-8s %-12s %-10s %-10s\n" "$symbol" "$stream_id" "$status" "$progress" "$has_worktree"
    fi
  done

  echo "────────────────────────────────────────────────────────"
  echo ""
}

cmd_init() {
  local input="$1"
  local stream_id
  stream_id=$(normalize_stream_id "$input")

  if [[ -z "$stream_id" ]]; then
    echo "Invalid stream ID: $input" >&2
    return 1
  fi

  if ! stream_exists "$stream_id"; then
    echo "Stream not found: $stream_id" >&2
    echo "Create it first: ralph stream new"
    return 1
  fi

  if worktree_exists "$stream_id"; then
    echo "Worktree already exists for $stream_id"
    return 0
  fi

  local branch="ralph/$stream_id"
  local worktree_path="$WORKTREES_DIR/$stream_id"

  # Create branch from current HEAD if it doesn't exist
  if ! git show-ref --verify --quiet "refs/heads/$branch"; then
    git branch "$branch"
    echo "Created branch: $branch"
  fi

  # Create worktree
  mkdir -p "$WORKTREES_DIR"
  git worktree add "$worktree_path" "$branch"

  # Copy stream state to worktree
  local stream_dir="$RALPH_DIR/$stream_id"
  local wt_ralph_dir="$worktree_path/.ralph/$stream_id"
  mkdir -p "$wt_ralph_dir"
  cp -r "$stream_dir"/* "$wt_ralph_dir/"

  # Copy shared guardrails if exists
  if [[ -f "$RALPH_DIR/guardrails.md" ]]; then
    cp "$RALPH_DIR/guardrails.md" "$worktree_path/.ralph/"
  fi

  echo "Initialized worktree for $stream_id"
  echo "  Path: $worktree_path"
  echo "  Branch: $branch"
}

cmd_build() {
  local input="$1"
  local iterations="${2:-1}"
  local stream_id
  stream_id=$(normalize_stream_id "$input")

  if [[ -z "$stream_id" ]]; then
    echo "Invalid stream ID: $input" >&2
    return 1
  fi

  if ! stream_exists "$stream_id"; then
    echo "Stream not found: $stream_id" >&2
    return 1
  fi

  # Acquire lock
  if ! acquire_lock "$stream_id"; then
    return 1
  fi

  # Set up cleanup on exit
  trap "release_lock '$stream_id'" EXIT

  local stream_dir="$RALPH_DIR/$stream_id"
  local work_dir="$ROOT_DIR"

  # If worktree exists, use it
  if worktree_exists "$stream_id"; then
    work_dir="$WORKTREES_DIR/$stream_id"
    stream_dir="$work_dir/.ralph/$stream_id"
  fi

  echo "Running build for $stream_id"
  echo "  Work dir: $work_dir"
  echo "  Iterations: $iterations"
  echo ""

  # Run loop.sh with stream-specific paths
  cd "$work_dir"
  PRD_PATH="$stream_dir/prd.md" \
  PLAN_PATH="$stream_dir/plan.md" \
  PROGRESS_PATH="$stream_dir/progress.md" \
  ERRORS_LOG_PATH="$stream_dir/errors.log" \
  ACTIVITY_LOG_PATH="$stream_dir/activity.log" \
  RUNS_DIR="$stream_dir/runs" \
    "$SCRIPT_DIR/loop.sh" build "$iterations"
}

cmd_merge() {
  local input="$1"
  local stream_id
  stream_id=$(normalize_stream_id "$input")

  if [[ -z "$stream_id" ]]; then
    echo "Invalid stream ID: $input" >&2
    return 1
  fi

  if ! worktree_exists "$stream_id"; then
    echo "No worktree for $stream_id" >&2
    echo "Nothing to merge - stream ran in main worktree"
    return 1
  fi

  local status
  status=$(get_stream_status "$stream_id")
  if [[ "$status" != "completed" ]]; then
    echo "Stream $stream_id is not completed (status: $status)" >&2
    return 1
  fi

  local branch="ralph/$stream_id"
  local base_branch="main"

  # Check if main exists, otherwise use master
  if ! git show-ref --verify --quiet "refs/heads/main"; then
    if git show-ref --verify --quiet "refs/heads/master"; then
      base_branch="master"
    fi
  fi

  echo "Merging $stream_id to $base_branch..."

  # Switch to base branch
  git checkout "$base_branch"

  # Merge stream branch
  if git merge --ff-only "$branch"; then
    echo "Merged $branch to $base_branch (fast-forward)"
  else
    echo "Fast-forward not possible. Attempting regular merge..."
    git merge "$branch" -m "Merge $stream_id"
  fi

  echo ""
  echo "Stream $stream_id merged successfully"
  echo ""
  echo "Next steps:"
  echo "  git push origin $base_branch"
  echo "  ralph stream cleanup $input"
}

cmd_cleanup() {
  local input="$1"
  local stream_id
  stream_id=$(normalize_stream_id "$input")

  if [[ -z "$stream_id" ]]; then
    echo "Invalid stream ID: $input" >&2
    return 1
  fi

  if ! worktree_exists "$stream_id"; then
    echo "No worktree for $stream_id"
    return 0
  fi

  local worktree_path="$WORKTREES_DIR/$stream_id"

  echo "Removing worktree for $stream_id..."
  git worktree remove "$worktree_path" --force

  echo "Cleaned up $stream_id"
}

# ============================================================================
# Main
# ============================================================================

cmd="${1:-}"
shift || true

case "$cmd" in
  new)
    cmd_new "$@"
    ;;
  list)
    cmd_list
    ;;
  status)
    cmd_status
    ;;
  init)
    if [[ -z "${1:-}" ]]; then
      echo "Usage: ralph stream init <N>" >&2
      exit 1
    fi
    cmd_init "$1"
    ;;
  build)
    if [[ -z "${1:-}" ]]; then
      echo "Usage: ralph stream build <N> [iterations]" >&2
      exit 1
    fi
    cmd_build "$1" "${2:-1}"
    ;;
  merge)
    if [[ -z "${1:-}" ]]; then
      echo "Usage: ralph stream merge <N>" >&2
      exit 1
    fi
    cmd_merge "$1"
    ;;
  cleanup)
    if [[ -z "${1:-}" ]]; then
      echo "Usage: ralph stream cleanup <N>" >&2
      exit 1
    fi
    cmd_cleanup "$1"
    ;;
  *)
    echo "Ralph Stream - Multi-PRD parallel execution"
    echo ""
    echo "Usage:"
    echo "  ralph stream new              Create new stream (prd-1, prd-2, ...)"
    echo "  ralph stream list             List all streams"
    echo "  ralph stream status           Show detailed status"
    echo "  ralph stream init <N>         Initialize worktree for parallel execution"
    echo "  ralph stream build <N> [n]    Run n build iterations in stream"
    echo "  ralph stream merge <N>        Merge completed stream to main"
    echo "  ralph stream cleanup <N>      Remove stream worktree"
    echo ""
    echo "Examples:"
    echo "  ralph stream new              # Creates prd-1"
    echo "  ralph stream build 1 5        # Run 5 iterations on prd-1"
    echo "  ralph stream init 1           # Create worktree for parallel work"
    echo "  ralph stream build 1 &        # Run in background"
    echo "  ralph stream build 2 &        # Run another in parallel"
    ;;
esac
